language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update
  # - sudo apt-get install libgtest-dev
  # - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    # - gcc-5
    - g++-5

script: 
  - $CXX --version
  - git clone https://github.com/google/googletest.git
  - cd googletest/googletest
  - mkdir build ; cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../../googlemock
  - mkdir build ; cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../../..  
  - make
  - sudo cp bin/libghost.so /usr/local/lib/
  # - sudo cp test/lib/libg*.a /usr/local/lib/
  - export LD_LIBRARY_PATH=/usr/local/lib/
  - sudo ldconfig
  - make test
  - cd test/bin && for i in $(ls); do ./$i; done
  # - valgrind --leak-check=full --show-reachable=yes bin/ghost --auto
  # - valgrind --tool=cachegrind bin/ghost --auto
  