language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9
    packages:
      - g++-6
      - clang-3.9


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER=g++-6

    - os: osx
      osx_image: xcode8
      compiler: clang
      env: COMPILER=clang++-3.9


before_install:
  - if [ "$COMPILER" = "g++-6"        ]; then export CXX="g++-6" CC="gcc-6";     fi
  - if [ "$COMPILER" = "clang++-3.9" ]; then export CXX="clang++" CC="clang";    fi

- git clone https://github.com/google/googletest.git

# install GTest
  - cd googletest/googletest
  - mkdir build ; cd build
  - cmake .. -DMAKE_INSTALL_PREFIX=../../../test/
  - cat Makefile | grep install:
  - make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - cd ../..

# install GMock
  - cd googlemock
  - mkdir build ; cd build
  - cmake .. -DMAKE_INSTALL_PREFIX=../../../test/
  - cat Makefile | grep install:
  - make
  - sudo make install
  - sudo cp -a include/gmock /usr/include
  - sudo cp -a libgmock_main.so libgmock.so /usr/lib/
  - cd ../../..


before_script:
  - if [ "$COMPILER" = "g++-6"        ]; then export CXX="g++-6" CC="gcc-6";     fi
  - if [ "$COMPILER" = "clang++-3.9" ]; then export CXX="clang++" CC="clang";    fi


script:
  - echo $CXX
  - $CXX --version

# install GHOST
  - export LD_LIBRARY_PATH=/usr/local/lib/
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
  - sudo make install
  - cd ..

# make and run tests
  - cd test  
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../bin && for i in $(ls); do ./$i; done


branches:
  only:
    - master
    - adaptive_search
