addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9
    packages:
      - g++-6
      - clang-3.9
      - valgrind

os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-6

    - compiler: clang
      env: COMPILER=clang++-3.9

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt-get -qq update;    fi

before_script:
    - if [ "$COMPILER" = "g++-6"        ]; then export CXX="g++-6" CC="gcc-6";              fi
    - if [ "$COMPILER" = "clang++-3.9"  ]; then export CXX="clang++-3.9" CC="clang-3.9";    fi
  
script:
  - echo $CXX
  - $CXX --version

  - git clone https://github.com/google/googletest.git

# install GTest
  - cd googletest/googletest
  - mkdir build ; cd build
  - cmake ..
  - make
  - cp -r ../include/* ../../../test/include/
  - cp libg*a ../../../test/lib/

# install GMock
  - cd ../../googlemock
  - mkdir build ; cd build
  - cmake ..
  - make
  - cp -r ../include/* ../../../test/include/
  - cp libg*a ../../../test/lib/
  - cd ../../..  

# install GHOST
  - export LD_LIBRARY_PATH=/usr/local/lib/
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
  - sudo make install
  - cd ..

# - make CXX=g++-5
# - sudo make install

# make and run tests
  - make test
  - cd test/bin && for i in $(ls); do ./$i; done

# - valgrind --leak-check=full --show-reachable=yes bin/ghost --auto
# - valgrind --tool=cachegrind bin/ghost --auto
