sudo: false
language: cpp
compiler:
  - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

script: 
  - $CXX --version
  - make test
  - test/bin/*
  # - valgrind --leak-check=full --show-reachable=yes bin/ghost --auto
  # - valgrind --tool=cachegrind bin/ghost --auto
  