language: cpp

matrix:
  include:
    # Ubuntu 14.04 Trusty with gcc
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
    	  sources:
      	    - ubuntu-toolchain-r-test
    	  packages:
      	    - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    # Ubuntu 14.04 Trusty with clang
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
    	  sources:
      	    - llvm-toolchain-trusty-5.0
    	  packages:
      	    - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    # Mac OSX
    - os: osx
      osx_image: xcode8
        
before_install:
    - eval "${MATRIX_EVAL}"
    
script:
  - echo $CXX
  - $CXX --version

  - git clone https://github.com/google/googletest.git

# install GTest
  - cd googletest/googletest
  - mkdir build ; cd build
  - cmake ..
  - make
  - sudo cp -r ../include/gtest /usr/local/include
  - sudo cp lib/libgtest_main.a lib/libgtest.a /usr/local/lib/
  - cd ../..

# install GMock
  - cd googlemock
#  - mkdir build ; cd build
#  - cmake ..
#  - make
  - sudo cp -r ../include/gmock /usr/local/include
#  - sudo cp libgmock_main.a libgmock.a /usr/local/lib/
  - cd ../../..

# install GHOST
  - export LD_LIBRARY_PATH=/usr/local/lib/
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
  - sudo make install
  - cd ..

# make and run tests
  - cd tests  
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../bin && for i in $(ls); do ./$i; done

branches:
  only:
    - master
    - develop
    - adaptive_search
    - develop
