language: cpp

addons:
  apt:
    sources:
      # for g++
      - ubuntu-toolchain-r-test
      # for CMake
      - george-edison55-precise-backports
      # for clang stdlib
#      - llvm-toolchain-precise-3.9
    packages:
      - cmake-data
      - cmake
#      - g++-6
#      - clang-3.9

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: 
        - g++-7
#        - clang
#      env: COMPILER=g++-6
      env: 
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode10.1
#      compiler: clang
#      env: COMPILER=clang++-3.9

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
#  - if [ "$COMPILER" = "g++-6"        ]; then export CXX="g++-6" CC="gcc-6";     fi
#  - if [ "$COMPILER" = "clang++-3.9" ]; then export CXX="clang++" CC="clang";    fi

script:
  - echo $CXX
  - $CXX --version

  - git clone https://github.com/google/googletest.git

# install GTest
  - cd googletest/googletest
  - mkdir -p build ; cd build
  - cmake ..
  - make all
  - sudo cp -r ../include/gtest /usr/local/include
  - sudo cp lib/libgtest_main.a lib/libgtest.a /usr/local/lib/
  - cd ../..

# install GMock
  - cd googlemock
  - mkdir -p build ; cd build
#  - cmake ..
#  - make
  - sudo cp -r ../include/gmock /usr/local/include
#  - sudo cp lib/libgmock_main.a lib/libgmock.a /usr/local/lib/
  - cd ../../..

# install GHOST
  - export LD_LIBRARY_PATH=/usr/local/lib/
  - mkdir -p build
  - cd build
  - cmake ..
  - make VERBOSE=1
  - sudo make install
  - cd ..

# make and run tests
  - mkdir -p tests
  - cd tests  
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - cd ../bin && for i in $(ls); do ./$i; done

branches:
  only:
    - master
    - develop
    - adaptive_search
    - no_template
