sudo: false
language: cpp
compiler:
  - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

script: 
  - $CXX --version
  - mkdir test/bin test/obj
  - make test
  - ls test/*
  - cd bin && for i in $(ls); do ./$i; done
  # - valgrind --leak-check=full --show-reachable=yes bin/ghost --auto
  # - valgrind --tool=cachegrind bin/ghost --auto
  