language: cpp

addons:
  apt:
    sources:
      #- ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9
    packages:
      #- g++-6
      #- clang-3.9

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      #env: COMPILER=g++-6

    - os: osx
      osx_image: xcode8
      compiler: clang
      #env: COMPILER=clang++-3.9

before_script:
  #- if [ "$COMPILER" = "g++-6"        ]; then export CXX="g++-6" CC="gcc-6";     fi
  #- if [ "$COMPILER" = "clang++-3.9" ]; then export CXX="clang++" CC="clang";    fi

script:
  - echo $CXX
  - $CXX --version

  - git clone https://github.com/google/googletest.git

# install GTest
  - cd googletest/googletest
  - mkdir build ; cd build
  - cmake ..
  - make
  - sudo cp -r ../include/gtest /usr/local/include
  - sudo cp libgtest_main.a libgtest.a /usr/local/lib/
  - cd ../..

# install GMock
  - cd googlemock
  - mkdir build ; cd build
  - cmake ..
  - make
  - sudo cp -r ../include/gmock /usr/local/include
  - sudo cp libgmock_main.a libgmock.a /usr/local/lib/
  - cd ../../..

# install GHOST
  - export LD_LIBRARY_PATH=/usr/local/lib/
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
  - sudo make install
  - cd ..

# make and run tests
  - cd tests  
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../bin && for i in $(ls); do ./$i; done

branches:
  only:
    - master
    - adaptive_search
    - develop
